# Generated by Django 5.1.2 on 2024-10-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("matricula", models.CharField(max_length=4, unique=True)),
                ("departamento", models.CharField(max_length=100)),
                ("data_admissao", models.DateField()),
                ("data_desligamento", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        max_length=10,
                    ),
                ),
                (
                    "nivel_escolaridade",
                    models.CharField(
                        choices=[
                            ("Ensino Médio Completo", "Ensino Médio Completo"),
                            ("Graduação", "Graduação"),
                            ("Pós-Graduação", "Pós-Graduação"),
                            ("Técnico", "Técnico"),
                        ],
                        max_length=50,
                    ),
                ),
                ("graduacao", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tipo_contratacao",
                    models.CharField(
                        choices=[("CLT", "CLT"), ("PJ", "PJ"), ("Outros", "Outros")],
                        max_length=20,
                    ),
                ),
                ("cargo_inicial", models.CharField(max_length=100)),
                ("cargo_atual", models.CharField(max_length=100)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pagamento_por_fora",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.CharField(
                        choices=[("Horista", "Horista"), ("Mensalista", "Mensalista")],
                        max_length=20,
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
