# Generated by Django 5.1.2 on 2024-10-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="descricao_cargo",
            field=models.FileField(
                blank=True, null=True, upload_to="descricoes_cargo/"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nivel_escolaridade",
            field=models.CharField(
                choices=[
                    ("Ensino Médio Completo", "Ensino Médio Completo"),
                    ("Graduação", "Graduação"),
                    ("Pós-Graduação", "Pós-Graduação"),
                    ("Técnico", "Técnico"),
                ],
                default="Ensino Médio Completo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="status",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=10,
            ),
        ),
    ]
