# Generated by Django 5.1.2 on 2024-10-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0002_funcionario_descricao_cargo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cbo", models.CharField(max_length=10, unique=True)),
                (
                    "descricao_cargo",
                    models.FileField(
                        blank=True, null=True, upload_to="descricoes_cargo/"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="descricao_cargo",
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nivel_escolaridade",
            field=models.CharField(
                choices=[
                    ("Sem Escolaridade", "Sem Escolaridade"),
                    ("Ensino Fundamental Incompleto", "Ensino Fundamental Incompleto"),
                    ("Ensino Fundamental Completo", "Ensino Fundamental Completo"),
                    ("Ensino Médio Incompleto", "Ensino Médio Incompleto"),
                    ("Ensino Médio Completo", "Ensino Médio Completo"),
                    ("Técnico", "Técnico"),
                    ("Tecnólogo", "Tecnólogo"),
                    ("Graduação Incompleta", "Graduação Incompleta"),
                    ("Graduação", "Graduação"),
                    ("Pós-Graduação", "Pós-Graduação"),
                    ("Mestrado", "Mestrado"),
                    ("Doutorado", "Doutorado"),
                ],
                default="Ensino Médio Completo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo_atual",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargo_atual",
                to="funcionarios.cargo",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo_inicial",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargo_inicial",
                to="funcionarios.cargo",
            ),
        ),
    ]
